//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSessions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ft_Excersises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ft_Excersises()
        {
            this.ft_TrainingExcersises = new HashSet<ft_TrainingExcersises>();
        }
    
        public int Id { get; set; }
        public string ExcersiseName { get; set; }
        public string Description { get; set; }
        public int SeasonPart { get; set; }
        public int ExcersiseCategory { get; set; }
        public bool GroupByCategory { get; set; }
    
        public virtual ft_ExcersiseCategory ft_ExcersiseCategory { get; set; }
        public virtual ft_SeasonPart ft_SeasonPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ft_TrainingExcersises> ft_TrainingExcersises { get; set; }
    }
}
