//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingSessions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ft_Category> ft_Category { get; set; }
        public virtual DbSet<ft_ExcersiseCategory> ft_ExcersiseCategory { get; set; }
        public virtual DbSet<ft_Excersises> ft_Excersises { get; set; }
        public virtual DbSet<ft_Hall> ft_Hall { get; set; }
        public virtual DbSet<ft_SeasonPart> ft_SeasonPart { get; set; }
        public virtual DbSet<ft_Seasons> ft_Seasons { get; set; }
        public virtual DbSet<ft_Signings> ft_Signings { get; set; }
        public virtual DbSet<ft_TrainingExcersises> ft_TrainingExcersises { get; set; }
        public virtual DbSet<ft_Trainings> ft_Trainings { get; set; }
    }
}
