//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoney
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incomes
    {
        public int Id { get; set; }
        public int Account { get; set; }
        public int Year { get; set; }
        public int Period { get; set; }
        public int IncomeCategory { get; set; }
        public System.DateTime PlannedDate { get; set; }
        public double PlannedAmount { get; set; }
        public Nullable<System.DateTime> RealDate { get; set; }
        public Nullable<double> RealAmount { get; set; }
        public bool Closed { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual IncomeCategories IncomeCategories { get; set; }
        public virtual Periods Periods { get; set; }
        public virtual Years Years { get; set; }
    }
}
