//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMoney
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<AccountTypes> AccountTypes { get; set; }
        public virtual DbSet<BudgetIncomes> BudgetIncomes { get; set; }
        public virtual DbSet<BudgetOutcomes> BudgetOutcomes { get; set; }
        public virtual DbSet<IncomeCategories> IncomeCategories { get; set; }
        public virtual DbSet<Incomes> Incomes { get; set; }
        public virtual DbSet<OutcomeCategories> OutcomeCategories { get; set; }
        public virtual DbSet<Outcomes> Outcomes { get; set; }
        public virtual DbSet<Periods> Periods { get; set; }
        public virtual DbSet<Transfers> Transfers { get; set; }
        public virtual DbSet<Years> Years { get; set; }
    }
}
