//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcersiseBelongsToSeasonParts
    {
        public int Id { get; set; }
        public int Excersise { get; set; }
        public int SeasonPart { get; set; }
    
        public virtual Excersises Excersises { get; set; }
        public virtual SeasonParts SeasonParts { get; set; }
    }
}
