//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class Excersises
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excersises()
        {
            this.ExcersiseBelongsToCategory = new HashSet<ExcersiseBelongsToCategory>();
            this.ExcersiseBelongsToSeasonParts = new HashSet<ExcersiseBelongsToSeasonParts>();
            this.TrainingExcersises = new HashSet<TrainingExcersises>();
        }
        [Display(Name="Id")]
        public int Id { get; set; }
        [Display(Name = "Název")]
        public string ExcersiseName { get; set; }
        [AllowHtml]
        [Display(Name = "Popis cvièení")]
        public string Description { get; set; }
        [Display(Name = "Krátky popis cvièení")]
        public string ShortDescript { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcersiseBelongsToCategory> ExcersiseBelongsToCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcersiseBelongsToSeasonParts> ExcersiseBelongsToSeasonParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingExcersises> TrainingExcersises { get; set; }
    }
}
