//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ExcersiseBelongsToCategory> ExcersiseBelongsToCategory { get; set; }
        public virtual DbSet<ExcersiseBelongsToSeasonParts> ExcersiseBelongsToSeasonParts { get; set; }
        public virtual DbSet<ExcersiseCategories> ExcersiseCategories { get; set; }
        public virtual DbSet<Excersises> Excersises { get; set; }
        public virtual DbSet<PlayerFunctions> PlayerFunctions { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<PlayerSigningToTrainings> PlayerSigningToTrainings { get; set; }
        public virtual DbSet<SeasonParts> SeasonParts { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<TeamPlayers> TeamPlayers { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TrainingExcersises> TrainingExcersises { get; set; }
        public virtual DbSet<TrainingFocuses> TrainingFocuses { get; set; }
        public virtual DbSet<TrainingLocations> TrainingLocations { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
        public virtual DbSet<TrainingSchemeModels> TrainingSchemeModels { get; set; }
        public virtual DbSet<TrainingSchemePartModels> TrainingSchemePartModels { get; set; }
    }
}
