//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerFunctions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerFunctions()
        {
            this.TeamPlayers = new HashSet<TeamPlayers>();
        }
    
        public int Id { get; set; }
        public string PlayerFunctionName { get; set; }
        public bool IsPlayer { get; set; }
        public bool IsGoalie { get; set; }
        public bool IsTrainer { get; set; }
        public bool IsManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamPlayers> TeamPlayers { get; set; }
    }
}
