//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSigningToTrainings
    {
        public int Id { get; set; }
        public int Training { get; set; }
        public int Player { get; set; }
        public bool Status { get; set; }
        public byte[] PlayerSignedDate { get; set; }
        public System.DateTime SignedDate { get; set; }
    
        public virtual Players Players { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
