//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SeasonParts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeasonParts()
        {
            this.ExcersiseBelongsToSeasonParts = new HashSet<ExcersiseBelongsToSeasonParts>();
            this.TrainingFocuses = new HashSet<TrainingFocuses>();
            this.Trainings = new HashSet<Trainings>();
            this.TrainingSchemeModels = new HashSet<TrainingSchemeModels>();
        }
        
        [Display(Name = "Id")]
        public int Id { get; set; }
        [Display(Name = "Název èásti sezóny")]
        public string SeasonPartName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcersiseBelongsToSeasonParts> ExcersiseBelongsToSeasonParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingFocuses> TrainingFocuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainings> Trainings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingSchemeModels> TrainingSchemeModels { get; set; }
    }
}
