//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FloorballTrainingSessions
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Trainings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainings()
        {
            this.PlayerSigningToTrainings = new HashSet<PlayerSigningToTrainings>();
            this.TrainingExcersises = new HashSet<TrainingExcersises>();
        }
    
        public int Id { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public System.DateTime MeetDate { get; set; }
        public System.DateTime SigningLimitDate { get; set; }
        public int TrainingLocation { get; set; }
        public int Team { get; set; }
        public int Season { get; set; }
        public int SeasonPart { get; set; }
        public Nullable<int> TrainingFocus { get; set; }
        public Nullable<int> TrainingSchemeModel { get; set; }
        public double TrainingLength { get; set; }
        public bool PublishTraining { get; set; }
        public bool PublishExcersises { get; set; }
        [NotMapped]
        public int Excersisecount { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerSigningToTrainings> PlayerSigningToTrainings { get; set; }
        public virtual SeasonParts SeasonParts { get; set; }
        public virtual Seasons Seasons { get; set; }
        public virtual Teams Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingExcersises> TrainingExcersises { get; set; }
        public virtual TrainingFocuses TrainingFocuses { get; set; }
        public virtual TrainingLocations TrainingLocations { get; set; }
        public virtual TrainingSchemeModels TrainingSchemeModels { get; set; }
    }
}
