//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VCZ_CT_TYPES
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_Default { get; set; }
        public string U_NoPsRExp { get; set; }
        public string U_WIPNotPost { get; set; }
    }
}
