//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VCZ_CT_STATUS
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_Default { get; set; }
        public string U_StredUse { get; set; }
        public string U_StredDfl { get; set; }
        public string U_OperPl { get; set; }
        public string U_OperDflt { get; set; }
        public string U_OperAct { get; set; }
        public string U_OperPatt { get; set; }
        public string U_OperColr { get; set; }
        public string U_OperEfft { get; set; }
        public string U_BlockIn { get; set; }
        public string U_BlockOut { get; set; }
        public string U_BlockInt { get; set; }
        public string U_BlockInv { get; set; }
        public string U_BlockTms { get; set; }
        public string U_BlockMan { get; set; }
        public string U_BlockNPB { get; set; }
        public string U_EquipCr { get; set; }
        public string U_ContrCr { get; set; }
        public string U_Closed { get; set; }
        public string U_ApprLock { get; set; }
        public string U_WiPCalc { get; set; }
    }
}
