//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VCZ_CT_PRJ
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int DocEntry { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string U_Descript { get; set; }
        public string U_Series { get; set; }
        public string U_Type { get; set; }
        public string U_CardCode { get; set; }
        public string U_CardName { get; set; }
        public string U_CntCode { get; set; }
        public Nullable<decimal> U_Price { get; set; }
        public Nullable<System.DateTime> U_StartDat { get; set; }
        public Nullable<System.DateTime> U_EndDate { get; set; }
        public Nullable<System.DateTime> U_ActStart { get; set; }
        public Nullable<System.DateTime> U_ActEndDt { get; set; }
        public Nullable<System.DateTime> U_DelDate { get; set; }
        public Nullable<System.DateTime> U_AcptDate { get; set; }
        public string U_CurSourc { get; set; }
        public string U_DocCurr { get; set; }
        public Nullable<decimal> U_DocRate { get; set; }
        public Nullable<decimal> U_SysRate { get; set; }
        public string U_Rezijni { get; set; }
        public string U_BlockNPB { get; set; }
        public string U_Status { get; set; }
        public string U_EmpNo { get; set; }
        public string U_SmlCode { get; set; }
        public string U_SmlName { get; set; }
        public string U_SmlDesc { get; set; }
        public string U_SmlOrdN { get; set; }
        public Nullable<decimal> U_SmlRev { get; set; }
        public Nullable<decimal> U_SmlExp { get; set; }
        public string U_FaktType { get; set; }
        public string U_FaktItm { get; set; }
        public string U_FinType { get; set; }
        public string U_SmlVers { get; set; }
        public Nullable<System.DateTime> U_ValidFr { get; set; }
        public Nullable<System.DateTime> U_ValidTo { get; set; }
        public Nullable<int> U_HoldRecs { get; set; }
        public Nullable<int> U_EquipID { get; set; }
        public Nullable<int> U_ContrID { get; set; }
        public string U_PaymGrp { get; set; }
        public Nullable<decimal> U_PlaRev { get; set; }
        public Nullable<decimal> U_PlaRevFC { get; set; }
        public Nullable<decimal> U_PlaRevSC { get; set; }
        public Nullable<decimal> U_ActRev { get; set; }
        public Nullable<decimal> U_ActRevFC { get; set; }
        public Nullable<decimal> U_ActRevSC { get; set; }
        public Nullable<decimal> U_PlaExp { get; set; }
        public Nullable<decimal> U_PlaExpFC { get; set; }
        public Nullable<decimal> U_PlaExpSC { get; set; }
        public Nullable<decimal> U_ActExp { get; set; }
        public Nullable<decimal> U_ActExpFC { get; set; }
        public Nullable<decimal> U_ActExpSC { get; set; }
        public string U_AttPath { get; set; }
        public Nullable<short> U_DonePrc { get; set; }
        public Nullable<short> U_ProbRealO { get; set; }
        public Nullable<short> U_DonePrAR { get; set; }
        public string U_MainPrj { get; set; }
        public string U_GenATmpl { get; set; }
    }
}
