//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VST_OPPOR
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> U_Prc { get; set; }
    }
}
