//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VST_MM
    {
        public int DocEntry { get; set; }
        public Nullable<int> DocNum { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<short> Instance { get; set; }
        public Nullable<int> Series { get; set; }
        public string Handwrtten { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string U_user { get; set; }
        public Nullable<System.DateTime> U_date { get; set; }
        public string U_City { get; set; }
        public Nullable<int> U_Territory { get; set; }
        public string U_BP_Code { get; set; }
        public string U_BP_Name { get; set; }
        public string U_BP_Code2 { get; set; }
        public string U_BP_Name2 { get; set; }
        public string U_Contact { get; set; }
        public string U_Position { get; set; }
        public string U_Contact2 { get; set; }
        public string U_Position2 { get; set; }
        public string U_Customer { get; set; }
        public string U_MeetType { get; set; }
        public string U_Agenda { get; set; }
        public string U_Summary { get; set; }
        public string U_Cooperation { get; set; }
        public string U_Decision_date { get; set; }
        public string U_Real_date { get; set; }
        public Nullable<decimal> U_business_exp { get; set; }
        public string U_Currency { get; set; }
        public string U_Type { get; set; }
        public string U_Offer { get; set; }
        public string U_Offer_Send { get; set; }
        public string U_Next_meeting { get; set; }
        public string U_Competitors { get; set; }
        public string U_repeated { get; set; }
        public string U_Perspective { get; set; }
        public string U_Perspective_desc { get; set; }
        public string U_Decision_maker { get; set; }
        public string U_Position_DM { get; set; }
        public string U_Meeting_date { get; set; }
        public string U_Solvency { get; set; }
        public string U_Evaluation { get; set; }
        public string U_Information { get; set; }
        public Nullable<System.DateTime> U_date_crated { get; set; }
        public Nullable<System.DateTime> U_Next_contact { get; set; }
        public string U_Contact_form { get; set; }
        public string U_Perc { get; set; }
        public string U_Status { get; set; }
        public string U_Comment { get; set; }
        public Nullable<int> U_Opportunity { get; set; }
        public string U_VST_Oppor_st { get; set; }
    }
}
