//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBO_TESTEntities1 : DbContext
    {
        public SBO_TESTEntities1()
            : base("name=SBO_TESTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_VCZ_CT_PRJ> C_VCZ_CT_PRJ { get; set; }
        public virtual DbSet<DLN1> DLN1 { get; set; }
        public virtual DbSet<INV1> INV1 { get; set; }
        public virtual DbSet<OCRD> OCRD { get; set; }
        public virtual DbSet<ODLN> ODLN { get; set; }
        public virtual DbSet<OINV> OINV { get; set; }
        public virtual DbSet<OQUT> OQUT { get; set; }
        public virtual DbSet<ORDR> ORDR { get; set; }
        public virtual DbSet<QUT1> QUT1 { get; set; }
        public virtual DbSet<RDR1> RDR1 { get; set; }
        public virtual DbSet<JDT1> JDT1 { get; set; }
        public virtual DbSet<OHEM> OHEM { get; set; }
        public virtual DbSet<OJDT> OJDT { get; set; }
        public virtual DbSet<C_VCZ_CT_STATUS> C_VCZ_CT_STATUS { get; set; }
        public virtual DbSet<C_VCZ_CT_TYPES> C_VCZ_CT_TYPES { get; set; }
        public virtual DbSet<C_VST_MM> C_VST_MM { get; set; }
        public virtual DbSet<C_VST_OPPOR> C_VST_OPPOR { get; set; }
    }
}
