//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VST
{
    using System;
    using System.Collections.Generic;
    
    public partial class OJDT
    {
        public Nullable<int> BatchNum { get; set; }
        public int TransId { get; set; }
        public string BtfStatus { get; set; }
        public string TransType { get; set; }
        public string BaseRef { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Memo { get; set; }
        public string Ref1 { get; set; }
        public string Ref2 { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<decimal> LocTotal { get; set; }
        public Nullable<decimal> FcTotal { get; set; }
        public Nullable<decimal> SysTotal { get; set; }
        public string TransCode { get; set; }
        public string OrignCurr { get; set; }
        public Nullable<decimal> TransRate { get; set; }
        public Nullable<int> BtfLine { get; set; }
        public string TransCurr { get; set; }
        public string Project { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> TaxDate { get; set; }
        public string PCAddition { get; set; }
        public Nullable<int> FinncPriod { get; set; }
        public string DataSource { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> UserSign { get; set; }
        public Nullable<short> UserSign2 { get; set; }
        public string RefndRprt { get; set; }
        public Nullable<int> LogInstanc { get; set; }
        public string ObjType { get; set; }
        public string Indicator { get; set; }
        public string AdjTran { get; set; }
        public string RevSource { get; set; }
        public Nullable<System.DateTime> StornoDate { get; set; }
        public Nullable<int> StornoToTr { get; set; }
        public string AutoStorno { get; set; }
        public string Corisptivi { get; set; }
        public Nullable<System.DateTime> VatDate { get; set; }
        public string StampTax { get; set; }
        public short Series { get; set; }
        public int Number { get; set; }
        public string AutoVAT { get; set; }
        public Nullable<short> DocSeries { get; set; }
        public string FolioPref { get; set; }
        public Nullable<int> FolioNum { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public string BlockDunn { get; set; }
        public string ReportEU { get; set; }
        public string Report347 { get; set; }
        public string Printed { get; set; }
        public string DocType { get; set; }
        public Nullable<int> AttNum { get; set; }
        public string GenRegNo { get; set; }
        public Nullable<int> RG23APart2 { get; set; }
        public Nullable<int> RG23CPart2 { get; set; }
        public Nullable<int> MatType { get; set; }
        public string Creator { get; set; }
        public string Approver { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<short> SeqCode { get; set; }
        public Nullable<int> Serial { get; set; }
        public string SeriesStr { get; set; }
        public string SubStr { get; set; }
        public string AutoWT { get; set; }
        public Nullable<decimal> WTSum { get; set; }
        public Nullable<decimal> WTSumSC { get; set; }
        public Nullable<decimal> WTSumFC { get; set; }
        public Nullable<decimal> WTApplied { get; set; }
        public Nullable<decimal> WTAppliedS { get; set; }
        public Nullable<decimal> WTAppliedF { get; set; }
        public Nullable<decimal> BaseAmnt { get; set; }
        public Nullable<decimal> BaseAmntSC { get; set; }
        public Nullable<decimal> BaseAmntFC { get; set; }
        public Nullable<decimal> BaseVtAt { get; set; }
        public Nullable<decimal> BaseVtAtSC { get; set; }
        public Nullable<decimal> BaseVtAtFC { get; set; }
        public string VersionNum { get; set; }
        public Nullable<int> BaseTrans { get; set; }
        public string ResidenNum { get; set; }
        public string OperatCode { get; set; }
        public string Ref3 { get; set; }
        public string SSIExmpt { get; set; }
        public string SignMsg { get; set; }
        public string SignDigest { get; set; }
        public string CertifNum { get; set; }
        public Nullable<int> KeyVersion { get; set; }
        public Nullable<int> CUP { get; set; }
        public Nullable<int> CIG { get; set; }
        public string SupplCode { get; set; }
        public Nullable<int> SPSrcType { get; set; }
        public Nullable<int> SPSrcID { get; set; }
        public Nullable<int> SPSrcDLN { get; set; }
        public string U_VCZ_6501 { get; set; }
        public string U_VCZ_7525 { get; set; }
        public string U_VCZ_7526 { get; set; }
        public Nullable<System.DateTime> U_VCZ_7527 { get; set; }
        public string U_VCZ_7528 { get; set; }
        public string U_VCZ_7529 { get; set; }
    }
}
